### PR TITLE
Ensure `makeSymbol` does not change currentPage

### LINKED ISSUE #351: Symbols are not rendering
| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**

The react-sketchapp/examples/symbols project renders properly

**Observed behavior:**

It reports an error

```
/Users/calvinchan/react-sketchapp/examples/symbols  [git:master][calvinchan@ip-10-1-1-107] [15:03]
> yarn render
yarn run v1.6.0
$ skpm-build --watch --run
🖨  Copied src/manifest.json in 9ms
Error: Cannot render into Symbols page
line: 3109
sourceURL: /Users/calvinchan/react-sketchapp/examples/symbols/symbols.sketchplugin/Contents/Sketch/my-command.js
column: 16
stack: render@/Users/calvinchan/react-sketchapp/examples/symbols/symbols.sketchplugin/Contents/Sketch/my-command.js:3109:16
/Users/calvinchan/react-sketchapp/examples/symbols/symbols.sketchplugin/Contents/Sketch/my-command.js:4629:30
__skpm_run@/Users/calvinchan/react-sketchapp/examples/symbols/symbols.sketchplugin/Contents/Sketch/my-command.js:33077:17
__skpm_run@[native code]
🔩  Built ./my-command.js in 3249ms
```

**How to reproduce:**

clone repository and run `yarn render`

(on yarn 1.6)

**Sketch version:**

50.2

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

### PR DESCRIPTION
**Pull request by jaridmargolin**
This is a quick patch to fix #351

Hopefully for a v3 release we can get around all of this hoopla by providing a more natural interface as explained in https://github.com/airbnb/react-sketchapp/issues/316#issuecomment-393725040

### CODE REVIEW

File: src/symbol.js [hunk 1]
```diff
@@ -44,8 +44,10 @@ const getExistingSymbols = (document: any) => {
 
     let symbolsPage = getSymbolsPage(document);
```
Comment (mathieudutour) [inline src/symbol.js]: IIRC, there is a document.getOrCreateSymbolPage() method used somewhere else already. We probably want to use that

Comment (jaridmargolin) [reply src/symbol.js]: I did see it used, but wasn't sure if its implementation was exactly the same as what was happening here.

I kicked the can down the road, because I wasn't entirely sure how long we would be keeping this current Symbols API.

The next thing up on my list is investigating how to control manually rendering SymbolMasters rather then relying on `inject`.

**Comment by porada** [comment]
@jaridmargolin Could you release a new version that includes this patch?

**Comment by jaridmargolin** [comment]
I actually do not have publish rights... but @mathieudutour does :)
